### ISSUE TITLE
doctrine-bundle-cache-clear issue 

### ISSUE THREAD

**Issue by ganeshssac** [someniatko/doctrine-bundle-cache-clear#1]
Hi Someniatko
I am getting following error on my docker contatiner running php:7.2-apache image  whiich runs inside AWS Elastic Beanstalk. Any help would be much appreciated. 
Would you able to guide on fixing this issue. 
Thanks in advance 
Ganesh

Script cache:clear returned with error code 255
!!  
!!  Fatal error: During class fetch: Uncaught ReflectionException: Class Symfony\Component\Form\FormTypeGuesserInterface not found in /var/www/html/vendor/symfony/doctrine-bridge/Form/DoctrineOrmTypeGuesser.php:25
!!  Stack trace:
!!  #0 /var/www/html/vendor/composer/ClassLoader.php(444): include('/var/www/html/v...')
!!  #1 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
!!  #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Bridge\\...')
!!  #3 [internal function]: spl_autoload_call('Symfony\\Bridge\\...')
!!  #4 /var/www/html/vendor/symfony/config/Resource/ClassExistenceResource.php(76): class_exists('Symfony\\Bridge\\...')
!!  #5 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(349): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
!!  #6 /var/www/html/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(312): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Symfony\\Bridge\\...', false)
!!  #7 /var/ww in /var/www/html/vendor/symfony/doctrine-bridge/Form/DoctrineOrmTypeGuesser.php on line 25
!!

**Comment by ganeshssac** [comment]
Hi 
Please find composerold.json and lock and Docker files attached.
composerold.json = renamed which was originally composer.json

[fastr-api-developissue.zip](https://github.com/someniatko/doctrine-bundle-cache-clear/files/3428244/fastr-api-developissue.zip)

**Comment by someniatko** [comment]
this is an issue reproducer, not a library :)
